name: Build and test

on:
  push:
    branches: [ main, rewrite ]
  pull_request:
    branches: [ main, rewrite ]

jobs:
  build:
    name: Swift ${{ matrix.swift.version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, ubuntu-22.04, windows-latest]
        swift: [
          { version: "5.7", branch: "swift-5.7.2-release", tag: "5.7.2-RELEASE" }
        ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: swift-actions/setup-swift@v1
      if: matrix.os != 'windows-latest'
      with:
        swift-version: ${{ matrix.swift.version }}
    - uses: compnerd/gha-setup-swift@main
      if: matrix.os == 'windows-latest'
      with:
        branch: ${{ matrix.swift.branch }}
        tag: ${{ matrix.swift.tag }}
    - run: |
        git config --global core.autocrlf input
      if: matrix.os == 'windows-latest'
    - uses: actions/checkout@v3
    - name: Build (Debug)
      run: swift --version build -v -c debug
    - name: Test (Debug)
      run: swift --version test -v -c debug
    - name: Build (Release)
      run: swift --version build -v -c release
    - name: Test (Release)
      run: swift test -c release -Xswiftc
