name: Check the format of the Swift code

on:
  push:
    branches: [ main-disabled, format-check ]
  pull_request:
    branches: [ main-disabled ]

jobs:
  check-format:
    name: Check the format of the code Swift
    runs-on: ubuntu-22.04
    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.7"
    - name: Swift version 
      run: swift --version

    - name: Clone swift-format
      uses: actions/checkout@v3
      with:
        repository: apple/swift-format
        ref: "0bc2f0381c72d66a949254af22208a81377cf717" # Change here the version of swift-format to use
        path: swift-format
    - name: Build swift-format
      run: |
        cd swift-format
        swift build -c debug
        install .build/debug/swift-format /usr/local/bin/
      shell: bash

    - uses: actions/checkout@v3
    - name: Run swift-format on the codebase
      run: swift-format lint --configuration .swift-format.json -s -r -p Sources Tests *.swift
